title: BDMIOM 2018
description: The website for the 1st international workshop on big data for marketing intellegence and operation management
google_analytics: UA-120456695-1
theme: jekyll-theme-leap-day
